### ISSUE TITLE
Queryng a variables instead of strings to Wikidata using WikidataQueryServiceR

### ISSUE THREAD

**Issue by ccamara** [bearloga/WikidataQueryServiceR#10]
Provided a vector of movies' names, I would like to know their genres querying  Wikidata.

Since I am a R user, I have recently discovered `WikidataQueryServiceR` which has exactly the same example I was looking for:

```R
library(WikidataQueryServiceR)

query_wikidata('SELECT DISTINCT
  ?genre ?genreLabel
 WHERE {
  ?film wdt:P31 wd:Q11424.
  ?film rdfs:label "The Cabin in the Woods"@en.
  ?film wdt:P136 ?genre.
 SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
 }')
    
## 5 rows were returned by WDQS
```

Unfortunately, this query uses a static text, so I would like to replace `The Cabin in the Woods` by a vector. In order to do, I tried with the following code:

```R
library(WikidataQueryServiceR)

example <- "The Cabin in the Woods" # Single string for testing purposes.

query_wikidata(paste('SELECT DISTINCT ?human ?humanLabel ?sex_or_gender  ?sex_or_genderLabel WHERE {
  ?human wdt:P31 wd:Q5.
  ?human rdfs:label', example, '@en.
  ?human wdt:P21 ?sex_or_gender.
 SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
  OPTIONAL { ?human wdt:P2561 ?name. }
}', sep = ""))
```

But that does not work as expected, as I get the following result:

`Error in FUN(X[[i]], ...) : Bad Request (HTTP 400).`

Is there any way to pass variables instead of fixed strings?

**Comment by bearloga** [comment]
Howdy! Okay, the problem is missing quotes in the query around the movie name.

`example <- '"The Cabin in the Woods"'` is a solution

BUT I would recommend this approach:

```R
library(WikidataQueryServiceR)
library(glue) # cleaner than paste for substituting placeholders

movie_query <- 'SELECT DISTINCT
  ?genre ?genreLabel
WHERE {
  ?film wdt:P31 wd:Q11424.
  ?film rdfs:label "${movie_title}"@en.
  ?film wdt:P136 ?genre.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}'

movie_title <- "The Cabin in the Woods"

query_wikidata(glue(movie_query, .open = "${"))
```

And what's nice is that if you have a vector of `movie_titles`, you can do:

```R
results <- lapply(movie_titles, function(movie_title) {
  result <- query_wikidata(glue(movie_query, .open = "${"))
  return(result)
})
```

Does that help?

**Comment by ccamara** [comment]
Thank you very much for your explanation! 

You were right, I forgot the double quotes. 

Your proposed approach works great, although I have to admit that I had never heard of `glue`before and I do not wholly understand its differences (I do understand that the query is much cleaner now).

I also love the approach regarding to having vector titles, which is what I really wanted to do. The output, though, is a list of dataframes. Would it be possible to have a single dataframe with all results appended as rows instead?

**Comment by bearloga** [comment]
You're welcome!

And yup, you can do the following:

```R
results <- do.call(rbind, lapply(movie_titles, function(movie_title) {
  result <- …
  result$title <- movie_title
  return(result)
}))
```

**or**

```R
names(movie_titles) <- movie_titles
results <- dplyr::bind_rows(lapply(…), .id = "title")
```

P.S. The difference between `glue` and `paste` becomes clearer the more things you need to substitute/inject into a string.

**Comment by ccamara** [comment]
Thanks again for your explanation!
